### ISSUE TITLE
Uncaught runtime errors pub.on is not a function

### ISSUE THREAD

**Issue by Goosie** [YakiHonne/yakihonne-web-app#3]
When I create an account, choosed a picture, and than login I get a screen with Uncaught runtime errors. Removing the error screen the account is created.
ERROR
pub.on is not a function
TypeError: pub.on is not a function
    at https://client.4zaps.com/static/js/bundle.js:8899:15
    at https://client.4zaps.com/static/js/bundle.js:182157:41
    at Array.forEach (<anonymous>)
    at ws.onopen (https://client.4zaps.com/static/js/bundle.js:182157:27)
ERROR
pub.on is not a function
TypeError: pub.on is not a function
    at https://client.4zaps.com/static/js/bundle.js:8899:15
    at https://client.4zaps.com/static/js/bundle.js:182157:41
    at Array.forEach (<anonymous>)
    at ws.onopen (https://client.4zaps.com/static/js/bundle.js:182157:27)
ERROR
pub.on is not a function
TypeError: pub.on is not a function
    at https://client.4zaps.com/static/js/bundle.js:8899:15
    at https://client.4zaps.com/static/js/bundle.js:182157:41
    at Array.forEach (<anonymous>)
    at ws.onopen (https://client.4zaps.com/static/js/bundle.js:182157:27)

Something I have activate or config in the code?

**Comment by Darecjo** [comment]
We will investigate the issue, you may clear up your browser cache and see how things goes. May I know know what browser your are using and if you have installed extensions such as alby or nos2x?

**Comment by Goosie** [comment]
I used chrome and firefox. On Chrome I used ALby and on Firefox nos2x-fox. I tested different situations and all of the heaven all is working now, probably indeed a cache issue. Thanks for the support, great work BTW.

**Comment by Darecjo** [comment]
you are most welcome, thank you for the feedback.
