### ISSUE TITLE
If the embedded post is a reply, it cannot be displayed.

### ISSUE THREAD

**Issue by Lokuyow** [YakiHonne/yakihonne-web-app#8]
**Describe the bug**
When embedding a post in an article using nostr:~, if it is a reply, the display shows 'The note does not seem to be found'.

**To Reproduce**
1. Create an article
2. Embed a reply post to someone using nostr:~ in the article
3. Preview the article or publish it to check
4. "The note does not seem to be found" is displayed

**Expected behavior**
Display the post even if it is a reply

**Video and Screenshots**
The post above is a regular post, and the one below is a reply post
![image](https://github.com/user-attachments/assets/50c64623-12c0-478b-9243-f7fe7d11da12)
https://yakihonne.com/notes/nevent1qgswcsk8v4qck0deepdtluag3a9rh0jh2d0wh0w9g53qg8a9x2xqvqqqyzu0q8lu9fqetpy9tgh25zyh7v0ey0jc79h5jrw6c6508q4zhyysc6dtl2v

**Device (please complete the following information):**
 - Windows 11
 - Google Chrome 129.0.6668.101

**Comment by Darecjo** [comment]
Checked, sorry for the late reply 🙏
